spring.application.name=inventoryMgtSystem
server.port=5050
#MYSQL CONNECTION
spring.application.name=InventoryMgtSystem


# 1. 資料庫連線 URL（若資料庫名稱不同請修改 test_db）
spring.datasource.url=jdbc:mysql://localhost:3306/inventory_db

# 2. 你的 MySQL 帳號與密碼（請改成你安裝時設定的密碼）
spring.datasource.username=root
spring.datasource.password=123456

# 3. 驅動程式類別
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. JPA / Hibernate 自動建表與方言
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# 5. 上傳檔案大小上限設定
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
secreteJwtString = "phegondev123456789phegondev123456789"